var person_directory_data = {
   "person_directory":{
      "persons":[
         {
            "student":{
               "name":"nabeel",
               "stu_num":"234342"
            }
         },
         {
            "student":{
               "name":"yin",
               "stu_num":"423423"
            }
         },
         {
            "faculty":{
               "name":"andruid",
               "designation":"prof"
            }
         },
         {
            "student":{
               "name":"bill",
               "stu_num":"4234234"
            }
         },
         {
            "student":{
               "name":"sashi",
               "stu_num":"5454"
            }
         },
         {
            "student":{
               "name":"jon",
               "stu_num":"656565"
            }
         }
      ],
      "simpl.type": "tests.person.PersonDirectory"
   }
};