var circle_scope = {
   "simpl_types_scope":{
      "name":"circleTScope",
      "class_descriptor":[
         {
            "simpl.id":"25724761",
            "name":"tests.circle.Point",
            "tag_name":"point",
            "field_descriptor":[
               {
                  "name":"x",
                  "type":"18",
                  "scalar_type":"int"
               },
               {
                  "name":"y",
                  "type":"18",
                  "scalar_type":"int"
               }
            ]
         },
         {
            "simpl.id":"3449340",
            "name":"tests.circle.Circle",
            "tag_name":"circle",
            "field_descriptor":[
               {
                  "name":"radius",
                  "type":"18",
                  "scalar_type":"int"
               },
               {
                  "name":"center",
                  "type":"3",
                  "element_class":"tests.circle.Point",                  
                  "element_class_descriptor":{
                     "simpl.ref":"25724761"
                  }
               }
            ]
         }
      ]
   }
};