var graph_collection_scope = {
   "simpl_types_scope":{
      "name":"containerTScope",
      "class_descriptor":[
         {
            "simpl.id":"30936685",
            "name":"tests.graph.collections.ClassA",
            "tag_name":"class_a",
            "described_class":"tests.graph.collections.ClassA",
            "described_class_simple_name":"ClassA",
            "described_class_package_name":"tests.graph.collections",
            "field_descriptor":[
               {
                  "name":"u",
                  "tag_name":"u",
                  "field":"u",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"30936685"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"w",
                  "tag_name":"w",
                  "field":"w",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"30936685"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.id":"5143025",
            "name":"tests.graph.collections.Container",
            "tag_name":"container",
            "described_class":"tests.graph.collections.Container",
            "described_class_simple_name":"Container",
            "described_class_package_name":"tests.graph.collections",
            "field_descriptor":[
               {
                  "name":"aObjects",
                  "tag_name":"a_objects",
                  "field":"aObjects",
                  "element_class":"tests.graph.collections.ClassA",
                  "is_generic":"true",
                  "type":"4",
                  "collection_type":"simpl.types.collection.ArrayList",
                  "collection_or_map_tag_name":"objectsA",
                  "wrapped":"true",
                  "field_type":"ArrayList",
                  "element_class_descriptor":{
                     "simpl.ref":"30936685"
                  },
                  "declaring_class_descriptor":{
                     "simpl.ref":"5143025"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         }
      ]
   }
};