var maps_data = {
   "translation_s":{
      "class_descriptor":[
         {
            "tag_name":"cd1",
            "field_descriptor":[
               {
                  "field_name":"fd3_cd1"
               },
               {
                  "field_name":"fd2_cd1"
               },
               {
                  "field_name":"fd1_cd1"
               }
            ]
         },
         {
            "tag_name":"cd2",
            "field_descriptor":[
               {
                  "field_name":"fd2_cd2"
               },
               {
                  "field_name":"fd3_cd2"
               },
               {
                  "field_name":"fd1_cd2"
               }
            ]
         }
      ],
  	  "simpl.type": "tests.maps.TranslationS"
   }
};