var person_directory_scope = {
   "simpl_types_scope":{
      "name":"personDirectoryTScope",
      "class_descriptor":[
         {
            "simpl.id":"1484678",
            "name":"tests.person.Person",
            "tag_name":"person",
            "described_class":"tests.person.Person",
            "described_class_simple_name":"Person",
            "described_class_package_name":"tests.person",
            "field_descriptor":[
               {
                  "simpl.id":"22052786",
                  "name":"name",
                  "tag_name":"name",
                  "field":"name",
                  "type":"18",
                  "scalar_type":"String",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"String",
                  "declaring_class_descriptor":{
                     "simpl.ref":"1484678"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.id":"24783265",
            "name":"tests.person.Student",
            "tag_name":"student",
            "described_class":"tests.person.Student",
            "described_class_simple_name":"Student",
            "described_class_package_name":"tests.person",
            "super_class":{
               "simpl.ref":"1484678"
            },
            "field_descriptor":[
               {
                  "simpl.ref":"22052786"
               },
               {
                  "name":"stuNum",
                  "tag_name":"stu_num",
                  "field":"stuNum",
                  "type":"18",
                  "scalar_type":"String",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"String",
                  "declaring_class_descriptor":{
                     "simpl.ref":"24783265"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.id":"16359413",
            "name":"tests.person.PersonDirectory",
            "tag_name":"person_directory",
            "described_class":"tests.person.PersonDirectory",
            "described_class_simple_name":"PersonDirectory",
            "described_class_package_name":"tests.person",
            "field_descriptor":[
               {
                  "name":"persons",
                  "tag_name":"persons",
                  "field":"persons",
                  "is_generic":"true",
                  "type":"4",
                  "collection_type":"simpl.types.collection.ArrayList",
                  "collection_or_map_tag_name":"",
                  "wrapped":"true",
                  "field_type":"ArrayList",
                  "declaring_class_descriptor":{
                     "simpl.ref":"16359413"
                  },
                  "polymorph_class_descriptors":{
                     "polymorph_class_descriptor":[
                        {
                           "simpl.ref":"24783265"
                        },
                        {
                           "simpl.id":"7804298",
                           "name":"tests.person.Faculty",
                           "tag_name":"faculty",
                           "described_class":"tests.person.Faculty",
                           "described_class_simple_name":"Faculty",
                           "described_class_package_name":"tests.person",
                           "super_class":{
                              "simpl.ref":"1484678"
                           },
                           "field_descriptor":[
                              {
                                 "simpl.ref":"22052786"
                              },
                              {
                                 "name":"designation",
                                 "tag_name":"designation",
                                 "field":"designation",
                                 "type":"18",
                                 "scalar_type":"String",
                                 "xml_hint":"XML_ATTRIBUTE",
                                 "field_type":"String",
                                 "declaring_class_descriptor":{
                                    "simpl.ref":"7804298"
                                 },
                                 "library_namespaces":{
                                    "library_namespace":[

                                    ]
                                 }
                              }
                           ]
                        }
                     ]
                  },
                  "polymorph_classes":{
                     "polymorph_class":[
                        {

                        },
                        {

                        }
                     ]
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.ref":"7804298"
         }
      ]
   }
};