var student_scope = {
   "simpl_types_scope":{
      "name":"studentTScope",
      "class_descriptor":[
         {
            "simpl.id":"22052786",
            "name":"tests.person.Person",
            "tag_name":"person",
            "described_class":"tests.person.Person",
            "described_class_simple_name":"Person",
            "described_class_package_name":"tests.person",
            "field_descriptor":[
               {
                  "simpl.id":"32487478",
                  "name":"name",
                  "tag_name":"name",
                  "field":"name",
                  "type":"18",
                  "scalar_type":"String",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"String",
                  "declaring_class_descriptor":{
                     "simpl.ref":"22052786"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.id":"28420709",
            "name":"tests.person.Student",
            "tag_name":"student",
            "described_class":"tests.person.Student",
            "described_class_simple_name":"Student",
            "described_class_package_name":"tests.person",
            "super_class":{
               "simpl.ref":"22052786"
            },
            "field_descriptor":[
               {
                  "simpl.ref":"32487478"
               },
               {
                  "name":"stuNum",
                  "tag_name":"stu_num",
                  "field":"stuNum",
                  "type":"18",
                  "scalar_type":"String",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"String",
                  "declaring_class_descriptor":{
                     "simpl.ref":"28420709"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         }
      ]
   }
};