var classAclassB_scope = {
   "simpl_types_scope":{
      "name":"classATScope",
      "class_descriptor":[
         {
            "simpl.id":"31544005",
            "name":"tests.graph.ClassB",
            "tag_name":"class_b",
            "described_class":"tests.graph.ClassB",
            "described_class_simple_name":"ClassB",
            "described_class_package_name":"tests.graph",
            "field_descriptor":[
               {
                  "name":"a",
                  "tag_name":"a",
                  "field":"a",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"31544005"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"b",
                  "tag_name":"b",
                  "field":"b",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"31544005"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"classA",
                  "tag_name":"class_a",
                  "field":"classA",
                  "element_class":"tests.graph.ClassA",
                  "type":"3",
                  "composite_tag_name":"class_a",
                  "field_type":"ClassA",
                  "element_class_descriptor":{
                     "simpl.id":"22743805",
                     "name":"tests.graph.ClassA",
                     "tag_name":"class_a",
                     "described_class":"tests.graph.ClassA",
                     "described_class_simple_name":"ClassA",
                     "described_class_package_name":"tests.graph",
                     "super_class":{
                        "name":"java.lang.Object",
                        "tag_name":"object",
                        "described_class":"java.lang.Object",
                        "described_class_simple_name":"Object",
                        "described_class_package_name":"java.lang",
                        "field_descriptor":[

                        ]
                     },
                     "field_descriptor":[
                        {
                           "name":"x",
                           "tag_name":"x",
                           "field":"x",
                           "type":"18",
                           "scalar_type":"int",
                           "xml_hint":"XML_ATTRIBUTE",
                           "field_type":"int",
                           "declaring_class_descriptor":{
                              "simpl.ref":"22743805"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        },
                        {
                           "name":"y",
                           "tag_name":"y",
                           "field":"y",
                           "type":"18",
                           "scalar_type":"int",
                           "xml_hint":"XML_ATTRIBUTE",
                           "field_type":"int",
                           "declaring_class_descriptor":{
                              "simpl.ref":"22743805"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        },
                        {
                           "name":"classB",
                           "tag_name":"class_b",
                           "field":"classB",
                           "element_class":"tests.graph.ClassB",
                           "type":"3",
                           "composite_tag_name":"class_b",
                           "field_type":"ClassB",
                           "element_class_descriptor":{
                              "simpl.ref":"31544005"
                           },
                           "declaring_class_descriptor":{
                              "simpl.ref":"22743805"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        },
                        {
                           "name":"classA",
                           "tag_name":"class_a",
                           "field":"classA",
                           "element_class":"tests.graph.ClassA",
                           "type":"3",
                           "composite_tag_name":"class_a",
                           "field_type":"ClassA",
                           "element_class_descriptor":{
                              "simpl.ref":"22743805"
                           },
                           "declaring_class_descriptor":{
                              "simpl.ref":"22743805"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        }
                     ]
                  },
                  "declaring_class_descriptor":{
                     "simpl.ref":"31544005"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.ref":"22743805"
         }
      ]
   }
};