var circle_scope = {
   "simpl_types_scope":{
      "name":"circleTScope",
      "class_descriptor":[
         {
            "simpl.id":"25724761",
            "name":"tests.circle.Point",
            "tag_name":"point",
            "described_class":"tests.circle.Point",
            "described_class_simple_name":"Point",
            "described_class_package_name":"tests.circle",
            "field_descriptor":[
               {
                  "name":"x",
                  "tag_name":"x",
                  "field":"x",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"25724761"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"y",
                  "tag_name":"y",
                  "field":"y",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"25724761"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.id":"3449340",
            "name":"tests.circle.Circle",
            "tag_name":"circle",
            "described_class":"tests.circle.Circle",
            "described_class_simple_name":"Circle",
            "described_class_package_name":"tests.circle",
            "field_descriptor":[
               {
                  "name":"radius",
                  "tag_name":"radius",
                  "field":"radius",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_LEAF",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"3449340"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"center",
                  "tag_name":"center",
                  "field":"center",
                  "element_class":"tests.circle.Point",
                  "type":"3",
                  "composite_tag_name":"center",
                  "field_type":"Point",
                  "element_class_descriptor":{
                     "simpl.ref":"25724761"
                  },
                  "declaring_class_descriptor":{
                     "simpl.ref":"3449340"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         }
      ]
   }
};