var collectionWrapScalar_data = {
   "collection_of_wrap_circles":{
      "str":"something",
      "collection_of_circles":{
         "circles":[
            {
               "radius":"1",
               "center":{
                  "x":"2",
                  "y":"3"
               }
            },
            {
               "radius":"1",
               "center":{
                  "x":"2",
                  "y":"4"
               }
            },
            {
               "radius":"1",
               "center":{
                  "x":"2",
                  "y":"5"
               }
            },
            {
               "radius":"1",
               "center":{
                  "x":"2",
                  "y":"6"
               }
            },
            {
               "radius":"1",
               "center":{
                  "x":"2",
                  "y":"7"
               }
            }
         ]
      },
      "dummy":[
         "10",
         "23"
      ],
      "yo":"1",
      "simpl.type":"tests.circle.CollectionOfCircles"
   }
};