var collectionOfCircles_data = {
   "collection_of_circles":{
      "circles":[
         {
            "radius":"1",
            "center":{
               "x":"2",
               "y":"3"
            }
         },
         {
            "radius":"1",
            "center":{
               "x":"2",
               "y":"4"
            }
         },
         {
            "radius":"1",
            "center":{
               "x":"2",
               "y":"5"
            }
         },
         {
            "radius":"1",
            "center":{
               "x":"2",
               "y":"6"
            }
         },
         {
            "radius":"1",
            "center":{
               "x":"2",
               "y":"7"
            }
         }
      ],
      "yo":"1"
   }
};