var collectionWrapScalar_scope = 
{
   "simpl_types_scope":{
      "name":"collectionOfWrapCirclesTScope",
      "class_descriptor":[
         {
            "simpl.id":"15020296",
            "name":"tests.circle.Point",
            "tag_name":"point",
            "described_class":"tests.circle.Point",
            "described_class_simple_name":"Point",
            "described_class_package_name":"tests.circle",
            "field_descriptor":[
               {
                  "name":"x",
                  "tag_name":"x",
                  "field":"x",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"15020296"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"y",
                  "tag_name":"y",
                  "field":"y",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"15020296"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.id":"19551481",
            "name":"tests.circle.CollectionOfCircles",
            "tag_name":"collection_of_circles",
            "described_class":"tests.circle.CollectionOfCircles",
            "described_class_simple_name":"CollectionOfCircles",
            "described_class_package_name":"tests.circle",
            "field_descriptor":[
               {
                  "name":"collectionOfCircles",
                  "tag_name":"collection_of_circles",
                  "field":"collectionOfCircles",
                  "element_class":"tests.circle.Circle",
                  "is_generic":"true",
                  "type":"4",
                  "collection_type":"simpl.types.collection.ArrayList",
                  "collection_or_map_tag_name":"circles",
                  "wrapped":"true",
                  "field_type":"ArrayList",
                  "element_class_descriptor":{
                     "simpl.id":"18237215",
                     "name":"tests.circle.Circle",
                     "tag_name":"circle",
                     "described_class":"tests.circle.Circle",
                     "described_class_simple_name":"Circle",
                     "described_class_package_name":"tests.circle",
                     "field_descriptor":[
                        {
                           "name":"radius",
                           "tag_name":"radius",
                           "field":"radius",
                           "type":"18",
                           "scalar_type":"int",
                           "xml_hint":"XML_LEAF",
                           "field_type":"int",
                           "declaring_class_descriptor":{
                              "simpl.ref":"18237215"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        },
                        {
                           "name":"center",
                           "tag_name":"center",
                           "field":"center",
                           "element_class":"tests.circle.Point",
                           "type":"3",
                           "composite_tag_name":"center",
                           "field_type":"Point",
                           "element_class_descriptor":{
                              "simpl.ref":"15020296"
                           },
                           "declaring_class_descriptor":{
                              "simpl.ref":"18237215"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        }
                     ]
                  },
                  "declaring_class_descriptor":{
                     "simpl.ref":"19551481"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"str",
                  "tag_name":"str",
                  "field":"str",
                  "type":"18",
                  "scalar_type":"String",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"String",
                  "declaring_class_descriptor":{
                     "simpl.ref":"19551481"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"dummyList",
                  "tag_name":"dummy_list",
                  "field":"dummyList",
                  "is_generic":"true",
                  "type":"5",
                  "scalar_type":"Integer",
                  "collection_type":"simpl.types.collection.ArrayList",
                  "xml_hint":"XML_ATTRIBUTE",
                  "collection_or_map_tag_name":"dummy",
                  "field_type":"ArrayList",
                  "declaring_class_descriptor":{
                     "simpl.ref":"19551481"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"yo",
                  "tag_name":"yo",
                  "field":"yo",
                  "type":"18",
                  "scalar_type":"int",
                  "xml_hint":"XML_LEAF",
                  "field_type":"int",
                  "declaring_class_descriptor":{
                     "simpl.ref":"19551481"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.ref":"18237215"
         }
      ]
   }
};