var diamond_scope = {
   "simpl_types_scope":{
      "name":"classDTScope",
      "class_descriptor":[
         {
            "simpl.id":"2771331",
            "name":"tests.graph.diamond.ClassD",
            "tag_name":"class_d",
            "described_class":"tests.graph.diamond.ClassD",
            "described_class_simple_name":"ClassD",
            "described_class_package_name":"tests.graph.diamond",
            "field_descriptor":[
               {
                  "name":"classA",
                  "tag_name":"class_a",
                  "field":"classA",
                  "element_class":"tests.graph.diamond.ClassA",
                  "type":"3",
                  "composite_tag_name":"class_a",
                  "field_type":"ClassA",
                  "element_class_descriptor":{
                     "simpl.id":"13086732",
                     "name":"tests.graph.diamond.ClassA",
                     "tag_name":"class_a",
                     "described_class":"tests.graph.diamond.ClassA",
                     "described_class_simple_name":"ClassA",
                     "described_class_package_name":"tests.graph.diamond",
                     "field_descriptor":[
                        {
                           "name":"x",
                           "tag_name":"x",
                           "field":"x",
                           "type":"18",
                           "scalar_type":"int",
                           "xml_hint":"XML_ATTRIBUTE",
                           "field_type":"int",
                           "declaring_class_descriptor":{
                              "simpl.ref":"13086732"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        },
                        {
                           "name":"y",
                           "tag_name":"y",
                           "field":"y",
                           "type":"18",
                           "scalar_type":"int",
                           "xml_hint":"XML_ATTRIBUTE",
                           "field_type":"int",
                           "declaring_class_descriptor":{
                              "simpl.ref":"13086732"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        },
                        {
                           "name":"classC",
                           "tag_name":"class_c",
                           "field":"classC",
                           "element_class":"tests.graph.diamond.ClassC",
                           "type":"3",
                           "composite_tag_name":"class_c",
                           "field_type":"ClassC",
                           "element_class_descriptor":{
                              "simpl.id":"11707096",
                              "name":"tests.graph.diamond.ClassC",
                              "tag_name":"class_c",
                              "described_class":"tests.graph.diamond.ClassC",
                              "described_class_simple_name":"ClassC",
                              "described_class_package_name":"tests.graph.diamond",
                              "field_descriptor":[
                                 {
                                    "name":"u",
                                    "tag_name":"u",
                                    "field":"u",
                                    "type":"18",
                                    "scalar_type":"int",
                                    "xml_hint":"XML_ATTRIBUTE",
                                    "field_type":"int",
                                    "declaring_class_descriptor":{
                                       "simpl.ref":"11707096"
                                    },
                                    "library_namespaces":{
                                       "library_namespace":[

                                       ]
                                    }
                                 },
                                 {
                                    "name":"w",
                                    "tag_name":"w",
                                    "field":"w",
                                    "type":"18",
                                    "scalar_type":"int",
                                    "xml_hint":"XML_ATTRIBUTE",
                                    "field_type":"int",
                                    "declaring_class_descriptor":{
                                       "simpl.ref":"11707096"
                                    },
                                    "library_namespaces":{
                                       "library_namespace":[

                                       ]
                                    }
                                 }
                              ]
                           },
                           "declaring_class_descriptor":{
                              "simpl.ref":"13086732"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        }
                     ]
                  },
                  "declaring_class_descriptor":{
                     "simpl.ref":"2771331"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"classB",
                  "tag_name":"class_b",
                  "field":"classB",
                  "element_class":"tests.graph.diamond.ClassB",
                  "type":"3",
                  "composite_tag_name":"class_b",
                  "field_type":"ClassB",
                  "element_class_descriptor":{
                     "simpl.id":"23505432",
                     "name":"tests.graph.diamond.ClassB",
                     "tag_name":"class_b",
                     "described_class":"tests.graph.diamond.ClassB",
                     "described_class_simple_name":"ClassB",
                     "described_class_package_name":"tests.graph.diamond",
                     "field_descriptor":[
                        {
                           "name":"x",
                           "tag_name":"x",
                           "field":"x",
                           "type":"18",
                           "scalar_type":"int",
                           "xml_hint":"XML_ATTRIBUTE",
                           "field_type":"int",
                           "declaring_class_descriptor":{
                              "simpl.ref":"23505432"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        },
                        {
                           "name":"y",
                           "tag_name":"y",
                           "field":"y",
                           "type":"18",
                           "scalar_type":"int",
                           "xml_hint":"XML_ATTRIBUTE",
                           "field_type":"int",
                           "declaring_class_descriptor":{
                              "simpl.ref":"23505432"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        },
                        {
                           "name":"classC",
                           "tag_name":"class_c",
                           "field":"classC",
                           "element_class":"tests.graph.diamond.ClassC",
                           "type":"3",
                           "composite_tag_name":"class_c",
                           "field_type":"ClassC",
                           "element_class_descriptor":{
                              "simpl.ref":"11707096"
                           },
                           "declaring_class_descriptor":{
                              "simpl.ref":"23505432"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        },
                        {
                           "name":"classX",
                           "tag_name":"class_x",
                           "field":"classX",
                           "element_class":"tests.graph.diamond.ClassX",
                           "type":"3",
                           "composite_tag_name":"class_x",
                           "field_type":"ClassX",
                           "element_class_descriptor":{
                              "simpl.id":"17296353",
                              "name":"tests.graph.diamond.ClassX",
                              "tag_name":"class_x",
                              "described_class":"tests.graph.diamond.ClassX",
                              "described_class_simple_name":"ClassX",
                              "described_class_package_name":"tests.graph.diamond",
                              "field_descriptor":[
                                 {
                                    "name":"u",
                                    "tag_name":"u",
                                    "field":"u",
                                    "type":"18",
                                    "scalar_type":"int",
                                    "xml_hint":"XML_ATTRIBUTE",
                                    "field_type":"int",
                                    "declaring_class_descriptor":{
                                       "simpl.ref":"17296353"
                                    },
                                    "library_namespaces":{
                                       "library_namespace":[

                                       ]
                                    }
                                 },
                                 {
                                    "name":"w",
                                    "tag_name":"w",
                                    "field":"w",
                                    "type":"18",
                                    "scalar_type":"int",
                                    "xml_hint":"XML_ATTRIBUTE",
                                    "field_type":"int",
                                    "declaring_class_descriptor":{
                                       "simpl.ref":"17296353"
                                    },
                                    "library_namespaces":{
                                       "library_namespace":[

                                       ]
                                    }
                                 }
                              ]
                           },
                           "declaring_class_descriptor":{
                              "simpl.ref":"23505432"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        }
                     ]
                  },
                  "declaring_class_descriptor":{
                     "simpl.ref":"2771331"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.ref":"11707096"
         },
         {
            "simpl.ref":"23505432"
         },
         {
            "simpl.ref":"13086732"
         },
         {
            "simpl.ref":"17296353"
         }
      ]
   }
};