var graph_collection_data = {
   "container":{
      "a_objects":{
         "objectsA":[
            {
               "simpl.id":"29147324",
               "u":"55",
               "w":"54"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "simpl.ref":"29147324"
            },
            {
               "u":"55",
               "w":"54"
            },
            {
               "u":"55",
               "w":"54"
            }
         ]
      },
      "simpl.type": "tests.graph.collections.Container"
   }
};