var maps_within_maps_scope = {
   "simpl_types_scope":{
      "name":"testingMapWithinMapsTScope",
      "class_descriptor":[
         {
            "simpl.id":"28637909",
            "name":"tests.maps.ClassDes",
            "tag_name":"class_des",
            "described_class":"tests.maps.ClassDes",
            "described_class_simple_name":"ClassDes",
            "described_class_package_name":"tests.maps",
            "field_descriptor":[
               {
                  "name":"tagName",
                  "tag_name":"tag_name",
                  "field":"tagName",
                  "map_key_field_name":"tagName",
                  "type":"18",
                  "scalar_type":"String",
                  "xml_hint":"XML_ATTRIBUTE",
                  "field_type":"String",
                  "declaring_class_descriptor":{
                     "simpl.ref":"28637909"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               },
               {
                  "name":"fieldDescriptorsByTagName",
                  "tag_name":"field_descriptors_by_tag_name",
                  "field":"fieldDescriptorsByTagName",
                  "element_class":"tests.maps.FieldDes",
                  "is_generic":"true",
                  "type":"6",
                  "collection_type":"simpl.types.collection.HashMap",
                  "collection_or_map_tag_name":"field_descriptor",
                  "field_type":"HashMap",
                  "element_class_descriptor":{
                     "simpl.id":"813251",
                     "name":"tests.maps.FieldDes",
                     "tag_name":"field_des",
                     "described_class":"tests.maps.FieldDes",
                     "described_class_simple_name":"FieldDes",
                     "described_class_package_name":"tests.maps",
                     "field_descriptor":[
                        {
                           "name":"fieldName",
                           "tag_name":"field_name",
                           "field":"fieldName",
                           "map_key_field_name":"fieldName",
                           "type":"18",
                           "scalar_type":"String",
                           "xml_hint":"XML_ATTRIBUTE",
                           "field_type":"String",
                           "declaring_class_descriptor":{
                              "simpl.ref":"813251"
                           },
                           "library_namespaces":{
                              "library_namespace":[

                              ]
                           }
                        }
                     ]
                  },
                  "declaring_class_descriptor":{
                     "simpl.ref":"28637909"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         },
         {
            "simpl.ref":"813251"
         },
         {
            "simpl.id":"2771331",
            "name":"tests.maps.TranslationS",
            "tag_name":"translation_s",
            "described_class":"tests.maps.TranslationS",
            "described_class_simple_name":"TranslationS",
            "described_class_package_name":"tests.maps",
            "field_descriptor":[
               {
                  "name":"entriesByTag",
                  "tag_name":"entries_by_tag",
                  "field":"entriesByTag",
                  "element_class":"tests.maps.ClassDes",
                  "is_generic":"true",
                  "type":"6",
                  "collection_type":"simpl.types.collection.HashMap",
                  "collection_or_map_tag_name":"class_descriptor",
                  "field_type":"HashMap",
                  "element_class_descriptor":{
                     "simpl.ref":"28637909"
                  },
                  "declaring_class_descriptor":{
                     "simpl.ref":"2771331"
                  },
                  "library_namespaces":{
                     "library_namespace":[

                     ]
                  }
               }
            ]
         }
      ]
   }
};